### ISSUE TITLE
Add to bookmarks leading to "The given key was not present in the dictionary"

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/CyclopsChat#43]
Today, I've tried to right-click a tab in CyclopsChat and add a room to bookmarks, which led to a message being printed to the chat log:
> Disconnect due 'The given key '\<some GUID>' was not present in the dictionary.'.

First of all, we should improve the error handling there, and also fix the issue.

**TODO:**
- [x] fix an issue with reconnection
- [ ] update SharpXMPP to a new version
- [x] fix the initial problem with rooms and keys
